<a href="https://colab.research.google.com/github/nicolasshart/pcd-aula03/blob/main/atvidade_analise_de_dados_com_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

dados

In [14]:
import numpy as np

dados = np.array([
    [120, 15000, 100, 125.00, 4],
    [135, 16200, 108, 120.00, 5],
    [98,  11700,  82, 119.39, 3],
    [150, 21000, 125, 140.00, 7],
    [175, 24500, 140, 140.00, 9],
    [160, 22400, 132, 140.00, 6],
    [110, 13200,  95, 120.00, 2]
])
dias = np.array(["Segunda","Terça","Quarta","Quinta","Sexta","Sábado","Domingo"])
nomes = np.array(["Pedidos","Faturamento","Clientes","Ticket","Reclamações"])

# colunas
ped, fat, cli, tick, rec = dados[:,0], dados[:,1], dados[:,2], dados[:,3], dados[:,4]

parte 1

In [15]:
print("linhas:", dados.shape[0], "| colunas:", dados.shape[1])
print("total:", dados.size, "| dimensões:", dados.ndim, "| dtype:", dados.dtype)
np.set_printoptions(suppress=True)

linhas: 7 | colunas: 5
total: 35 | dimensões: 2 | dtype: float64


parte 2

In [16]:
print("2.1 sexta:", dados[4])
print("2.2 faturamento:", dados[:,1])
print("2.3 reclamações:", dados[:,4])
print("2.4 quinta a domingo:\n", dados[3:])
print("2.5 pedidos, fat., clientes:\n", dados[:, :3])

2.1 sexta: [  175. 24500.   140.   140.     9.]
2.2 faturamento: [15000. 16200. 11700. 21000. 24500. 22400. 13200.]
2.3 reclamações: [4. 5. 3. 7. 9. 6. 2.]
2.4 quinta a domingo:
 [[  150. 21000.   125.   140.     7.]
 [  175. 24500.   140.   140.     9.]
 [  160. 22400.   132.   140.     6.]
 [  110. 13200.    95.   120.     2.]]
2.5 pedidos, fat., clientes:
 [[  120. 15000.   100.]
 [  135. 16200.   108.]
 [   98. 11700.    82.]
 [  150. 21000.   125.]
 [  175. 24500.   140.]
 [  160. 22400.   132.]
 [  110. 13200.    95.]]


parte 3

In [17]:
print("3.1 total pedidos:", np.sum(ped))
print("3.2 faturamento total:", np.sum(fat))
print("3.3 total clientes:", np.sum(cli))
print("3.4 média pedidos:", np.mean(ped))
print("3.5 média faturamento:", np.mean(fat))
print("3.6 média reclamações:", np.mean(rec))

3.1 total pedidos: 948.0
3.2 faturamento total: 124000.0
3.3 total clientes: 782.0
3.4 média pedidos: 135.42857142857142
3.5 média faturamento: 17714.285714285714
3.6 média reclamações: 5.142857142857143


parte 4

In [18]:
print("4.1 mais pedidos:", dias[np.argmax(ped)], "| menos:", dias[np.argmin(ped)])
print("4.2 maior fat.:", dias[np.argmax(fat)], "| menor:", dias[np.argmin(fat)])
print("4.3 amplitude:", np.max(fat) - np.min(fat))

4.1 mais pedidos: Sexta | menos: Quarta
4.2 maior fat.: Sexta | menor: Quarta
4.3 amplitude: 12800.0


parte 5

In [19]:
print("5.1 fat. > 20000:", dias[fat > 20000])
print("5.2 pedidos > 140:", dias[ped > 140])
print("5.3 reclamações > 6:", dias[rec > 6])
print("5.4 fat. com pedidos > 150:", fat[ped > 150])
print("5.5 abaixo da média:", np.sum(fat < np.mean(fat)))  # true conta 1

5.1 fat. > 20000: ['Quinta' 'Sexta' 'Sábado']
5.2 pedidos > 140: ['Quinta' 'Sexta' 'Sábado']
5.3 reclamações > 6: ['Quinta' 'Sexta']
5.4 fat. com pedidos > 150: [24500. 22400.]
5.5 abaixo da média: 4


parte 6

In [20]:
classificacao = np.where(fat >= 20000, "Alto desempenho", "Desempenho normal")
print("6.1", np.column_stack((dias, classificacao)))
print("6.2 alto desempenho:", np.sum(classificacao == "Alto desempenho"))

6.1 [['Segunda' 'Desempenho normal']
 ['Terça' 'Desempenho normal']
 ['Quarta' 'Desempenho normal']
 ['Quinta' 'Alto desempenho']
 ['Sexta' 'Alto desempenho']
 ['Sábado' 'Alto desempenho']
 ['Domingo' 'Desempenho normal']]
6.2 alto desempenho: 3


parte 7

In [21]:
media, desvio = np.mean(fat), np.std(fat)
print("média:", media, "| mediana:", np.median(fat), "| desvio:", desvio)
print("mín:", np.min(fat), "| máx:", np.max(fat))
print("coef. variação:", desvio / media)

média: 17714.285714285714 | mediana: 16200.0 | desvio: 4551.429468209041
mín: 11700.0 | máx: 24500.0
coef. variação: 0.2569355344956717


Tem grande variação. Média de 17.714, mediana de 16.200 e desvio de 4.551. O maior faturamento de 24.500 é mais que o dobro do menor de 11.700.

parte 8

In [22]:
print("8.1 médias:", np.mean(dados, axis=0))
print("8.2 máximos:", np.max(dados, axis=0))
print("8.3 mínimos:", np.min(dados, axis=0))

# variação relativa = desvio / média
cv = np.std(dados, axis=0) / np.mean(dados, axis=0)
print("8.4 cv:", cv)
print("maior variação:", nomes[np.argmax(cv)])

8.1 médias: [  135.42857143 17714.28571429   111.71428571   129.19857143
     5.14285714]
8.2 máximos: [  175. 24500.   140.   140.     9.]
8.3 mínimos: [   98.   11700.      82.     119.39     2.  ]
8.4 cv: [0.19067459 0.25693553 0.17584864 0.07360736 0.43390276]
maior variação: Reclamações


Tem a maior variação de 0,43, seguida pelo faturamento de 0,26. O ticket médio é o mais estável de 0,07.

parte 9

In [23]:
i = np.argmax(fat)
print("9.1 melhor dia:", dias[i])
print("9.2 também mais pedidos?", i == np.argmax(ped))
print("9.3 também mais reclamações?", i == np.argmax(rec))
print("9.4 >150 pedidos e fat. >20000:", np.sum((ped > 150) & (fat > 20000)))

9.1 melhor dia: Sexta
9.2 também mais pedidos? True
9.3 também mais reclamações? True
9.4 >150 pedidos e fat. >20000: 2


parte 10

In [24]:
print("RESUMO DA SEMANA")
print(f"total de pedidos: {np.sum(ped):.0f}")
print(f"faturamento total: R$ {np.sum(fat):,.2f}")
print(f"média diária de pedidos: {np.mean(ped):.2f}")
print(f"média diária de faturamento: R$ {np.mean(fat):,.2f}")
print(f"melhor dia: {dias[np.argmax(fat)]}")
print(f"pior dia: {dias[np.argmin(fat)]}")
print(f"maior nº de reclamações: {dias[np.argmax(rec)]} ({rec.max():.0f})")
print(f"dias de alto desempenho: {np.sum(fat >= 20000)}")

RESUMO DA SEMANA
total de pedidos: 948
faturamento total: R$ 124,000.00
média diária de pedidos: 135.43
média diária de faturamento: R$ 17,714.29
melhor dia: Sexta
pior dia: Quarta
maior nº de reclamações: Sexta (9)
dias de alto desempenho: 3


parte 11 apoio

In [25]:
# correlação com reclamações
print("pedidos x reclamações:", np.corrcoef(ped, rec)[0,1])
print("pedidos x faturamento:", np.corrcoef(ped, fat)[0,1])

pedidos x reclamações: 0.938533563702666
pedidos x faturamento: 0.9893559484402098


Teve desempenho diferent com faturamento total de 124.000, concentrado de quinta a sábado com todos acima de 20.000. Os outros quatro dias abaixo da média. Na quarta, pior dia com 98 pedidos e 11.700, e na sexta, melhor em faturamento de 24.500, mas também com mais 9 reclamações.
Pedidos e faturamento têm relação de 0,99 e pedidos e reclamações, 0,94. Quanto mais pedidos, mais reclamações. Com só 7 dias, isso é indício.